apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-server-staging
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      service: core-server-staging
  template:
    metadata:
      labels:
        type: backend
        service: core-server-staging
    spec:
      containers:
        - name: container
          image: sellerspot/core-server-staging
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: core-server-staging
  namespace: staging
spec:
  type: NodePort
  ports:
    - port: 8000
  selector:
    type: backend
    service: core-server-staging
