apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-app-production
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
      service: core-app-production
  template:
    metadata:
      labels:
        type: frontend
        service: core-app-production
    spec:
      containers:
        - name: container
          image: sellerspot/core-app-production
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: core-app-production
  namespace: production
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    type: frontend
    service: core-app-production
